### ISSUE TITLE
Revert back to WinRM communicator for Windows boxes

### ISSUE THREAD

**Issue by gusztavvargadr** [gusztavvargadr/packer#101]
SSH commnicator seems to have issues with some providers, see #97 for more details. Keep supporting SSH but have WinRM as the default for Vagrant boxes.

**Comment by gusztavvargadr** [comment]
@mkg20001 a couple of days probably, by early next week.

**Comment by gusztavvargadr** [comment]
@mkg20001 let me know which box(es) you use and for which provider, I can start with building those then.

**Comment by mkg20001** [comment]
@gusztavvargadr That would be gusztavvargadr/windows10 for virtualbox

**Comment by mkg20001** [comment]
@gusztavvargadr WinRM seems to be timing out. See https://gitlab.com/mkg20001-foss/pneumon/-/jobs/123966981 (last few lines) for a log

**Comment by gusztavvargadr** [comment]
@mkg20001 it boots after a sysprep, so a first boot takes a lot of time, though the timeout should be 10 minutes. You can take a look to increase that timeout or would it be possible to give it some more resources (CPU and RAM)? The default 1 vCPU / 1 GB is only a bare minimum.

https://www.vagrantup.com/docs/vagrantfile/machine_settings.html#config-vm-boot_timeout

**Comment by gusztavvargadr** [comment]
@mkg20001 thanks, I'll take another look as well how it boots with the defaults, I test the boxes with 2 vCPUs and 4 GBs of RAM, then they boot in a few minutes with no problem.

If you don't need Windows 10 but Server is also fine, I will publish soon boxes for that as well (also Windows 10 1809 and Windows Server 2019).

**Comment by mkg20001** [comment]
I retried the job with windows10 and it seems to have worked (but there are some network issues now). https://gitlab.com/mkg20001-foss/pneumon/-/jobs/124217065
I've retried windows10 https://gitlab.com/mkg20001-foss/pneumon/-/jobs/124297380 but it's still in progress.
w10e is still running, too, https://gitlab.com/mkg20001-foss/pneumon/-/jobs/124297980 (restarted because vagrant decided to download in slowmo - eta 46h -.-)

> If you don't need Windows 10 but Server is also fine, I will publish soon boxes for that as well (also Windows 10 1809 and Windows Server 2019) - Server boots a lot faster.

That would be great

**Comment by TonyApuzzo** [comment]
w16s is working for me on Hyper-V as long as I use an Externally Routed Bridge for the network.  If I select "Default Network" NAT network or a private VLAN network adapter (even if it has Internet access, just lacking host access) then it hangs during the WinRM step.  I am not sure if this is new or existing behavior actually since I usually use External Bridge.  I just accidentally picked "Default Network" and noticed that it didn't work.

**Comment by gusztavvargadr** [comment]
@TonyApuzzo I see issues with the Default Switch as well. In general, I see its DHCP is sometimes not working perfectly, I think this is not an issue with the box, but with the OS implementation, could not completely figure it out yet. If you think, share your Vagrant logs and / or try to log in to the box and check the network configuration if it gets a proper IP.

I usually end up setting up either an external one as you suggest, or implement my own internal one. You can either do a standard internet connection sharing or configure your own NAT on Windows 10.

On Windows Server you don't even have the Default Switch, so you have to do the above anyway. This includes setting up at least a DHCP server and optionally RRAS as well. I'm planning to write a blog about all this :)

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network

**Comment by TonyApuzzo** [comment]
Agree that "Default Switch" is not ready for prime time.  I have settled on using External switches in the interests of expediency but having an easy way to get a functional NAT network (OOB functionality of vmware workstation) would be great.

**Comment by gusztavvargadr** [comment]
@TonyApuzzo @mkg20001 there are new releases of Windows Server 2016 available as well now:

https://app.vagrantup.com/gusztavvargadr/boxes/w16s
https://app.vagrantup.com/gusztavvargadr/boxes/w16sc

They boot a lot faster than the Windows 10 ones (even after Sysprep), I recommend these for automation scenarios :)
