### ISSUE TITLE
Change Request: Split Windows server 2016 and 2019 in vagrant cloud

### ISSUE THREAD

**Issue by mahmoud-ashi** [gusztavvargadr/packer#215]
Hi @gusztavvargadr. First of all, thank you so much for all the efforts you are putting on this project. Your vagrant boxes have saved me enormous time building and maintaining Windows base boxes for my work!

I have a small change request though. Currently in vagrant cloud, you have the following 2 boxes (Windows-10, and Windows-Server). This means if I want to use either windows 10 or windows server 2019, you can simply do

```
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
end
```
and 
```
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server"
end
```

However, to use windows server 2016, you need to add the version `config.vm.box_version = "1607.0.2008"`. While this is fine, this does not allow us (as far as I know), to check for updates since it will assume the 2019 is the latest version.

Could you consider splitting the Windows Sever 2016 and 2019 into 2 boxes/categories in the cloud so that we can always use it without hardcoding a version?

Best regards.

**Comment by gusztavvargadr** [comment]
@mahmoud-ashi thanks for your kind words, I'm glad that it adds value and this is my main motivation for this project ;)

Vagrant supports multiple box versioning constraints, not just the fixed number. For example, to do Windows Server **2016**, you can do:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server"
  config.vm.box_version = "~> 1607"
end
```

And for Windows Server **2019** you can go with:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server"
  config.vm.box_version = "~> 1809"
end
```

This will be future proof and would include the check for the updates without hardcoding the full version numbers.

Would this work for your use case? In that case I'd keep the boxes as they are (to keep their numbers also on a managable level) and would extend the documentation with this.

**Comment by mahmoud-ashi** [comment]
Thanks @gusztavvargadr. I read about this before but I don't know how I missed it here. That should work for me. Thanks a lot. Will close the ticket now :).

**Comment by mahmoud-ashi** [comment]
I guess I found some bug in vagrant. I have a vagrant file that looks like so
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #####################################################
  # VMs definition section
  #####################################################

  # Define and configure the Windows 10 box
  config.vm.define "windows_10" do |windows_10|
    windows_10.vm.box = "gusztavvargadr/windows-10"
  end

  # Define and configure the Windows Server 2019 box
  config.vm.define "windows_server_2019" do |windows_server_2019|
    windows_server_2019.vm.box = "gusztavvargadr/windows-server"
    windows_server_2019.vm.box_version = "~> 1809"
  end

  # Define and configure the Windows Server 2016 box
  config.vm.define "windows_server_2016" do |windows_server_2016|
    windows_server_2016.vm.box = "gusztavvargadr/windows-server"
    windows_server_2016.vm.box_version = "~> 1607"
  end

  #####################################################
  # VMs provisioning section
  #####################################################

  # Provision the machine
  config.vm.provision "shell", path: "./provision_windows.bat"
end
```

If I run `vagrant box update windows_10` or `vagrant box update windows_server_2019`, it pulls the new boxes correctly. However, if I run `vagrant box update windows_server_2016`, I get the following:
```
==> windows_server_2016: Checking for updates to 'gusztavvargadr/windows-server'
    windows_server_2016: Latest installed version: 1809.0.2008
    windows_server_2016: Version constraints: ~> 1607
    windows_server_2016: Provider: virtualbox
==> windows_server_2016: Box 'gusztavvargadr/windows-server' (v1809.0.2008) is running the latest version.
```

As you can see, it gets the right constraint, but nevertheless, it does not takes it into consideration. I also tried setting the constraint to `~> 1607.0.0` and the same result. Any ideas?

**Comment by gusztavvargadr** [comment]
@mahmoud-ashi I cannot reproduce the **update** issue. I tried both the per-machine and the per-environment version, with the same (correct) result.

Base configuration:

```
$ vagrant --version
Vagrant 2.2.10

$ vagrant plugin list
No plugins installed.

$ vagrant box list
gusztavvargadr/windows-server (virtualbox, 1607.0.2007)
gusztavvargadr/windows-server (virtualbox, 1809.0.2007)
```

With this the **2019** update results in:

```
$ vagrant box update windows_server_2019
==> windows_server_2019: Checking for updates to 'gusztavvargadr/windows-server'
    windows_server_2019: Latest installed version: 1809.0.2007
    windows_server_2019: Version constraints: ~> 1809
    windows_server_2019: Provider: virtualbox
==> windows_server_2019: Updating 'gusztavvargadr/windows-server' with provider 'virtualbox' from version
==> windows_server_2019: '1809.0.2007' to '1809.0.2008'...
==> windows_server_2019: Loading metadata for box 'https://vagrantcloud.com/gusztavvargadr/windows-server'
==> windows_server_2019: Adding box 'gusztavvargadr/windows-server' (v1809.0.2008) for provider: virtualbox
    windows_server_2019: Downloading: https://vagrantcloud.com/gusztavvargadr/boxes/windows-server/versions/1809.0.2008/providers/virtualbox.box
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    windows_server_2019:
    windows_server_2019: Calculating and comparing box checksum...
==> windows_server_2019: Successfully added box 'gusztavvargadr/windows-server' (v1809.0.2008) for 'virtualbox'!
```

Followed by the **2016** update:

```
$ vagrant box update windows_server_2016
==> windows_server_2016: Checking for updates to 'gusztavvargadr/windows-server'
    windows_server_2016: Latest installed version: 1607.0.2007
    windows_server_2016: Version constraints: ~> 1607
    windows_server_2016: Provider: virtualbox
==> windows_server_2016: Updating 'gusztavvargadr/windows-server' with provider 'virtualbox' from version
==> windows_server_2016: '1607.0.2007' to '1607.0.2008'...
==> windows_server_2016: Loading metadata for box 'https://vagrantcloud.com/gusztavvargadr/windows-server'
==> windows_server_2016: Adding box 'gusztavvargadr/windows-server' (v1607.0.2008) for provider: virtualbox
    windows_server_2016: Downloading: https://vagrantcloud.com/gusztavvargadr/boxes/windows-server/versions/1607.0.2008/providers/virtualbox.box
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    windows_server_2016:
    windows_server_2016: Calculating and comparing box checksum...
==> windows_server_2016: Successfully added box 'gusztavvargadr/windows-server' (v1607.0.2008) for 'virtualbox'!
```

This seems to be correct to me. The same happens when I do a `vagrant box update ` without any machine names, for the whole environment. Can you maybe double check your Vagrant version? I'm running this on Windows 10 version 2004, fully patched, with VirtualBox 6.1.12.

<hr>

Regarding the **prune** issue, I can confirm this would clear all the versions of the 2016 boxes, but only if there are no machines created. I personally think this makes sense, as prune operates on the global level of boxes, not per environment. 

```
$ vagrant box prune --dry-run
The following boxes will be kept...
gusztavvargadr/windows-server (virtualbox, 1809.0.2008)

Checking for older boxes...
Would remove gusztavvargadr/windows-server virtualbox 1607.0.2007
Would remove gusztavvargadr/windows-server virtualbox 1607.0.2008
Would remove gusztavvargadr/windows-server virtualbox 1809.0.2007
```

However, I think the workflow for these updates should be as follows:

1. Do a `vagrant box update` for the whole environment.
1. Destroy and recreate all the machines that have a newer box version.
1. Then run `vagrant box prune --keep-active-boxes`.

```
$ vagrant status
Current machine states:

windows_10                not created (virtualbox)
windows_server_2019       running (virtualbox)
windows_server_2016       running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

$ vagrant box prune --keep-active-boxes
The following boxes will be kept...
gusztavvargadr/windows-server (virtualbox, 1809.0.2008)

Checking for older boxes...
Removing box 'gusztavvargadr/windows-server' (v1607.0.2007) with provider 'virtualbox'...
Box 'gusztavvargadr/windows-server' (v1607.0.2008) with provider 'virtualbox' appears
to still be in use by at least one Vagrant environment. Removing
the box could corrupt the environment. We recommend destroying
these environments first:

windows_server_2016 (ID: 63c701d7e58b432a94691579e2c9d27f)

Are you sure you want to remove this box? [y/N] n
Removing box 'gusztavvargadr/windows-server' (v1809.0.2007) with provider 'virtualbox'...
```

This way you can [keep the box versions you are actually using](https://www.vagrantup.com/docs/cli/box#keep-active-boxes), but if you think this is counter-intuitive, I encourage you to open an issue for Vagrant itself, and maybe discuss it over there, I'm glad to join as well.

<hr>

I hope the above helps. I was struggling a lot with the box versions and whether to have different major versions in the same box on Vagrant Cloud or separately, but this seemed to be a good tradeoff between the number of boxes I have to maintain and the usability (you don't need to change box names for new versions, only the version in the Vagrant configuration, I think it is much more descriptive).

But as you can see, boxes like [windows-server](https://app.vagrantup.com/gusztavvargadr/boxes/windows-server) are simply aliases to other canonical boxes (in this case, [windows-server-standard](https://app.vagrantup.com/gusztavvargadr/boxes/windows-server-standard)), so I can always add other aliases like per major version, but then I'd prefer to do it for all the other boxes as well, with all the different editions, and it would quickly explode the number of boxes to maintain. An approach like tags for Docker images would be much more useful for this, and I hope Vagrant Cloud gets there once, this is also one of the reasons I chose the current way.

**Comment by mahmoud-ashi** [comment]
Thanks @gusztavvargadr. After upgrading the vagrant version, the update works now fine. Regarding the prune, I find this as a usability issue in vagrant. In my case, I use your boxes as base box and do some provisioning on top. Next, I package my own boxes and cache them. This means that in my normal flow, I use my cached boxes not directly yours. So if `prune` deletes the base boxes, this means that I will need to almost always pull again. Since this is not an issue with your boxes, I will close this ticket. Thanks again a lot for you support @gusztavvargadr .

**Comment by gusztavvargadr** [comment]
@mahmoud-ashi I see, having a machine created and floating around just for this is indeed sub-optimal.

Just curious, did you consider giving Packer a go instead of packaging with Vagrant? Let me know - open a new issue - if you need any help.
