### ISSUE TITLE
[Q] How are Windows 11 licenses handled?

### ISSUE THREAD

**Issue by bsdooby** [gusztavvargadr/packer#412]
I do not quite get how the prepared boxes handle licenses. Aren't the boxes the "free for 3 months" variants from Microsoft? After pruning (i.e., a new box has been imported), my freshly started box shows that the license expired.

**Comment by gusztavvargadr** [comment]
@bsdooby yes, Windows boxes are built with the evaluation versions, for [Windows 11](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-11-enterprise) it is indeed by default 90 days. To be able to use the box automatically, all prompts that are presented during a regular installation are turned off for the boxes I build.

You might need to wait a couple of minutes or reboot in order for activation to kick in and the notifiation to disappear, check [this similar issue](https://github.com/gusztavvargadr/packer/issues/241). I have never noticed any actual issues due to this, automated provisioning and every tool usage works as expected.

Please let me know if the above helps resolving your issue.

**Comment by bsdooby** [comment]
The same effect; I got an activation error 0xC004C032 at first. But after again trying a manual activation, the state changed.

**Comment by bsdooby** [comment]
...and now even the license state info in the lower right on the Desktop shows that the license is now valid for 90 days. Thank you again!

**Comment by gusztavvargadr** [comment]
@bsdooby thanks for reporting back and glad to hear it got resolved. I will look into later if there is an issue in the box that can be improved to do the activation automatically on first boot.
