### ISSUE TITLE
Error when build box

### ISSUE THREAD

**Issue by SimonKirkhamCL4U** [gusztavvargadr/packer#65]
When trying to run - 

.\ci.ps1 build w16s-vs17p-virtualbox-base

I first got the error -  
`Error: C:/Code/Devops/packer/src/core/cake/template.cake(61,3): error CS1501: No overload for method 'DeleteDirectory' takes 1 arguments`

I fixed the by modifying line 62 in template.cake to add a second parameter - 
DeleteDirectory(template.GetBuildDirectory(), true);

I then get the error - 

```
========================================
packer-build
========================================
Executing task: packer-build
w16s-vs17p-virtualbox-base: Version
w16s-vs17p-virtualbox-base: Restore
w16s-vs17p-virtualbox-base: Build
w16s-vs17p-virtualbox-base: Packer build template.json
virtualbox-ovf output will be in this color.

1 error(s) occurred:

* source_path is required
An error occurred when executing task 'packer-build'.
Error: Process exited with code 1.
```

**Comment by gusztavvargadr** [comment]
@SimonKirkhamCL4U sorry for the inconvenience and the late reply and thanks for reporting the issue.

There have been various updates to Cake core and its addins used here which turned out to be backwards incompatible. I've fixed them in #66, could you please try to check out that branch and try again? Try to clean your tools directory in the repo root except the newly added `tools/packages.config` if the compile error is not resolved.

For the seconds issue, you need a recursive build here as described in the [documentation](https://github.com/gusztavvargadr/packer#chaining-builds-further) as the build you try uses the output of other builds (I'll consider making this the default option as it makes sense). Try to run it like `.\ci.ps1 restore w16s-vs17p-virtualbox-base --recursive=true`.

Please let me know if it resolves the issue.
