### ISSUE TITLE
Broken networking driver in gusztavvargadr/w10e-vs17c on VirtualBox

### ISSUE THREAD

**Issue by tmm1** [gusztavvargadr/packer#72]
I just launched the gusztavvargadr/w10e-vs17c box and the networking is not working. Device Manager shows broken/missing drivers.

**Comment by tmm1** [comment]
I was able to fix this as follows:

```
config.vm.provider "virtualbox" do |v|
  v.customize ['modifyvm', :id, '--nictype1', '82540EM']
end
```

**Comment by gusztavvargadr** [comment]
@tmm1 thanks for raising the issue and proving a workaround.

May I ask what is your host OS and tools (Vagrant, VirtualBox) versions? I'd include then this in the description of the relevant boxes.

**Comment by tmm1** [comment]
I'm on macOS 10.12 using VirtualBox 5.1.28 and Vagrant 2.0.0

I think you can actually include this line in the Vagrantfile which is part of your box, and then users won't have to do anything special.

**Comment by tmm1** [comment]
The vagrant documentation also mentions you can specify this via the `nic_type` parameter to the `config.network` line. That is probably the best fix for the base Vagrantfile.

**Comment by tmm1** [comment]
The docs I was referring to: https://www.vagrantup.com/docs/virtualbox/networking.html#virtualbox-nic-type

And here's what I see for the Vagrantfile included with the box (located at `~/.vagrant.d/boxes/gusztavvargadr-VAGRANTSLASH-w10e-vs17c/0.8.0/virtualbox/Vagrantfile`):

```ruby
# The contents below were provided by the Packer Vagrant post-processor

Vagrant.configure("2") do |config|
  config.vm.base_mac = "0800272AED17"
end


# The contents below (if any) are custom contents provided by the
# Packer template during image build.
Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator = 'winrm'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.network :forwarded_port, guest: 3389, host: 33389, auto_correct: true
end
```

**Comment by gusztavvargadr** [comment]
@tmm1 thanks, I was considering adding that to the box settings later as well, but first I need to make sure it does not break other environments (e.g. when I test the box on a Windows host, that setting is not needed, we need to make sure it does not break anything on Windows and Linux hosts either). FYI, the settings you refer to are defined [here](https://github.com/gusztavvargadr/packer/blob/c826a383d6aa2503b89c56573b49b671a77c8554/src/w/packer/postprocessors/vagrant-virtualbox/Vagrantfile).

Currently I have limited resources for building and testing boxes (I build and test only on local Windows hosts), and due to the limited support for nested virtualization (only available for Hyper-V of the providers I target now) I cannot use hosted services for this, but I'll try to build a "local" setup where I can test with other host OSes as well. If this or any other similar setting turns out to be working for all them, then I'll be glad to include it in the box configuration. For now I have raised #73 for this.

Thanks again!

**Comment by tmm1** [comment]
According to the vagrant documentation, the `nic_type` setting is specific to virtualbox only. I think it would be very safe for you to add as a default. But I understand you would like to test further and make sure it works across other platforms.

**Comment by gusztavvargadr** [comment]
@tmm1 yeah, I will test it on Windows, and if it works, I'll include it in the next release. For now I'll just mention in the docs (a hotfix with even only a Vagrantfile change would require to re-download several GBs). I also want to check first if other boxes are affected or not.

Btw, if you agree, I'll close this case now (as you were so kind to provide a workaround :), you can follow #73 to see how the update goes.
