### ISSUE TITLE
w16s-dc: docker daemon is not running

### ISSUE THREAD

**Issue by marcindulak** [gusztavvargadr/packer#75]
I'm using https://app.vagrantup.com/gusztavvargadr/boxes/w16s-dc version 0.8.0
Can you reproduce this error:

![screenshot from 2017-11-17 15-27-15](https://user-images.githubusercontent.com/3178318/32952135-947c6726-cbac-11e7-86d7-a209916dac4c.png)

It looks like https://success.docker.com/KBase/Docker_for_Windows_fails_with_a_daemon_not_running_message
but I'm also changing the box hostname and restarting the box https://github.com/moby/moby/issues/30239

**Comment by gusztavvargadr** [comment]
@marcindulak please note that this setup contains Docker for Windows' Community Editition, which defaults to Linux containers after installation. As mentioned in the box documentation, this is not supported in the VirtualBox image as VirtualBox itself does not support nested virtualization, and running Linux containers would require Hyper-V-based isolation.

You will need to switch to Windows containers as described [here](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers).

After that, the local service list should container a `Docker Engine` service running as well. I have just verified that this works as expected (I've tested the `hello-world` and `microsoft/dotnet` images as well).

Please make sure you select Windows containers and let me know if that solves the problem.

**Comment by gusztavvargadr** [comment]
@marcindulak FYI I have an experimental box just published with Windows Server 2016 Core (that is, no GUI) and Docker Enterprise. This has Docker as a proper service, no login and / or manual configuration is required to initialize, you can launch containers right after the machine boots. You can still use `vagrant rdp` or `vagrant powershell`, the box size is also significantly smaller: https://app.vagrantup.com/gusztavvargadr/boxes/w16sc-de.

**Comment by marcindulak** [comment]
https://app.vagrantup.com/gusztavvargadr/boxes/w16sc-de works out-of-the box for me, but still having problems with https://app.vagrantup.com/gusztavvargadr/boxes/w16s-dc. I noticed that I must run docker as vagrant user, but this together with the cli switch https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10#2-switch-to-windows-containers still is not enough. Can you reproduce this?

![screenshot from 2017-11-20 11-13-29](https://user-images.githubusercontent.com/3178318/33013501-9acfab3a-cde4-11e7-9df5-18c150ac6317.png)

**Comment by gusztavvargadr** [comment]
@marcindulak to me, unlike in your sample, the second `docker run` succeeds after the switch (even with the Docker popups kept open). Depending on your resources, it might take some time to do the switch (however, to me it worked within a few seconds). Indeed, the first approach by default tries to start the Linux Containers, which requires Hyper-V isolation, but that will not work under VirtualBox.

As far as I know, the Docker Community Edition (the *-dc boxes) works by design like this, that is, you need to log on to start the Docker Service as well, at least I don't know how to start it properly as a service, so this will not be a proper unattended setup. This works well for development scenarios (like with the Visual Studio boxes, where you probably want to log on anyway), but I think this is not a supported use case for deployment setups (that's why I started building the Enterprise Edition versions). However, I've noticed that doing a `& $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon` before logging on (like through `vagrant powershell`) works, when you log on, it will try the Windows Containers first. Maybe you can try invoking this call as a regular Vagrant Powershell provisioner step?

Let me know what is your exact scenario if the above does not work, I can try to build and publish an image for that. Also, it would probably make sense for me to include this step in the next version of the boxes (that is, launch into Windows Containers automatically), since the Linux Containers do not work with VirtualBox anyway :)

**Comment by marcindulak** [comment]
It would be good if the https://app.vagrantup.com/gusztavvargadr/boxes/w16s-dc (or maybe you want to make yet another box) was prepared for windows containers. I'm not successful with the command line switch. The VM has 2GB RAM and 1 core.
The powershell cli switch run during vagrant provisioning seems did not have any effect.

While performing the cli switch from within the running box in powershell, login as vagrant user, sometimes cli exits after a second without any error output, sometimes it fails after a longer time, like on the attached screenshot.

![screenshot from 2017-11-21 09-31-07](https://user-images.githubusercontent.com/3178318/33062490-c2e1f432-ce9f-11e7-8cb0-9d8790f4aa6e.png)

Docker's "An error occured: Time out has expired and the operation has not been completed" popup comes in by itself shortly after login I think.

**Comment by marcindulak** [comment]
With https://app.vagrantup.com/gusztavvargadr/boxes/w16s-dc,
command line switch is not working for me (with "The operation has timed out." this time). Only the GUI menu switch to windows containers works, and the daemon survives `vagrant reload` in a functional state.

![screenshot from 2017-11-22 13-52-14](https://user-images.githubusercontent.com/3178318/33128460-c3cc50b6-cf8c-11e7-8576-16b0ea7cdce6.png)

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# 1. GUI=1 vagrant up
# 2. login as vagrant
# 3. docker run microsoft/dotnet-samples:dotnetapp  # fails
# 4. & 'c:\Program Files\Docker\Docker\DockerCli.exe" -SwitchDaemon  # fails
# 5. Switch to windows containers using Docker GUI  # the above docker run works
# 6. GUI=1 vagrant reload
# 7. login as vagrant and wait for Docker to start

# http://stackoverflow.com/questions/23926945/specify-headless-or-gui-from-command-line
def gui_enabled?
  !ENV.fetch('GUI', '').empty?
end

Vagrant.configure(2) do |config|
  config.vm.define "windows" do |machine|
    machine.vm.box = "gusztavvargadr/w16s-dc"
    machine.vm.box_url = machine.vm.box
    machine.vm.provider "virtualbox" do |p|
      p.memory = 2048  # Windows is greedy
      p.cpus = 1
      p.gui = gui_enabled?
    end
    machine.ssh.shell = "powershell"
  end
  config.vm.define "windows" do |machine|
    # https://github.com/gusztavvargadr/packer/issues/75
    machine.vm.provision :shell, :inline => 'if (Test-Path $Env:ProgramFiles\Docker\Docker\DockerCli.exe) { & "$Env:ProgramFiles\\Docker\\Docker\\DockerCli.exe" -SwitchDaemon }'
    machine.vm.provision :shell, :inline => '(Get-WmiObject Win32_ComputerSystem).Rename("myhost")'
    machine.vm.provision :shell, :inline => 'Restart-Computer -Force'
  end
end
```

**Comment by gusztavvargadr** [comment]
@marcindulak yeah, the *-dc boxes I have are built with Docker for Windows **Community** Edition. As far as I know, this is designed to be working like that, you need to log in in order to start the Docker service.

If you don't need the Windows GUI, I recommend to use https://app.vagrantup.com/gusztavvargadr/boxes/w16sc-de which works with Docker **Enterprise**, and that starts the service without any interaction. If you need the GUI, we can easily build a box with Windows Server 2016 Standard with GUI with Docker Enterprise as well. Or you can go back to the basics, and use the pure server https://app.vagrantup.com/gusztavvargadr/boxes/w16s and provision Docker Enterprise for yourself https://docs.docker.com/engine/installation/windows/docker-ee/#install-docker-ee :)

Let me know.

**Comment by marcindulak** [comment]
Installing DE on `gusztavvargadr/w16s` followed by `Restart-Computer -Force` gives me a usable Docker daemon on a GUI Windows 2016 Server, so I don't need any extra box.

```
machine.vm.provision :shell, :inline => 'Install-Module DockerProvider -Force'
machine.vm.provision :shell, :inline => 'Install-Package Docker -ProviderName DockerProvider -Force'
```

**Comment by gusztavvargadr** [comment]
Glad to hear it works now!
